import React from "react";
import type { Metadata } from "next";
import "@styles/scss/main.scss";
import TopBar from "@widgets/TopBar";
import Header from "@widgets/Header";
import Footer from "@widgets/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" text-gray-700">
        <TopBar />
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
